// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{ 
  //vec3 dark_blue = vec3(0.0, 0.0, 0.5);
  //vec3 darK_green = vec3(0.0, 0.5, 0.0);
  //vec3 dark_grey = vec3(0.25, 0.25, 0.25);
  //vec3 light_grey = vec3(0.5, 0.5, 0.5);
  vec3 white = vec3(1.0, 1.0, 1.0);


  vec3 dark_blue = vec3(0.0, 0.0, 1.0);
  vec3 darK_green = vec3(0.0, 1.0, 0.0);
  vec3 light_grey = vec3(0.75, 0.75, 0.75);
  vec3 dark_grey = vec3(0.05, 0.05, 0.05);


  float angle = M_PI*animation_seconds* 0.5; //moon speed
  float moon = mix(0.0, 1.0, is_moon);
    
  vec3 pos = sphere_fs_in;
  float x_rot = cos(angle) * pos.x + sin(angle) * pos.z; 
  float y_rot = pos.y;
  float z_rot = cos(angle) * pos.z - sin(angle) * pos.x;
  vec3 pos_rotate = vec3(x_rot, y_rot, z_rot);

  pos = mix(pos, pos_rotate, moon);
  
  // float pearl = perlin_noise(pos);
  // pearl = clamp(0.5*pearl + 0.5, 0.0, 1.0);

  float pearl1 = perlin_noise(pos);
  float pearl2 = perlin_noise(pos * 2.0);
  float pearl3 = perlin_noise(pos * 4.0);
  float pearl = pearl1 - pearl2 + pearl3;
  pearl = clamp(0.5*pearl + 0.4, 0.0, 1.0);


  vec3 color_earth = mix(dark_blue, darK_green, pearl);
  vec3 color_moon = mix(dark_grey, light_grey, pearl);

  vec3 diffuse = mix(color_earth, color_moon, moon);
  vec3 ambient = white;
  vec3 specular = mix(white, light_grey, moon);
  float pp = mix(200.0, 50.0, moon);

  float angle2 = M_PI*animation_seconds* 0.25; //light speed
  
  vec3 lightpos3 = vec3(10*cos(angle2), 7, 10*sin(angle2));
  vec4 lightpos4 = vec4(lightpos3, 1.0);
  vec4 lightview4 = view * lightpos4;
  vec3 lightview3 = lightview4.xyz;


  vec3 norm = normalize(normal_fs_in);
  vec3 viewww = normalize(-view_pos_fs_in.xyz);
  vec3 lig = normalize(lightview3 - view_pos_fs_in.xyz);

  color = blinn_phong(ambient, diffuse, specular, pp, norm, viewww, lig);
}
